SELECT ICECREAM_INFO.FLAVOR 
FROM ICECREAM_INFO 
JOIN FIRST_HALF 
ON ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR 
WHERE ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based' 
AND FIRST_HALF.TOTAL_ORDER > 3000 
ORDER BY FIRST_HALF.TOTAL_ORDER desc;